version: "3.8"

services:

  app:
    build: .
    container_name: node_app
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: